### ISSUE TITLE
Sieve rules are not applied when using 'managesieve' in dovecot_protocols

### ISSUE THREAD

**Issue by ganto** [debops/ansible-dovecot#6]
Altough the ManageSieve service is setup and started when adding `managesieve` to `dovecot_protocols`, the mail delivery will ignore the mail filtering rules in the users `sieve/` directory.

**Comment by drybjed** [comment]
I think the best way to fix that would be to add Postfix as a dependency to `debops.dovecot` and configure required options using Postfix dependency variables, similarly to how `debops.mailman` or `debops.smstools` work. LMTP support would be nice to have, this can be combined with Amavis for spam filtering later.

**Comment by ganto** [comment]
LMTP is now fully supported, so that the sieve rules are applied without manual fiddling. The setup is documented at [debops.dovecot: Enable server-side mail filtering with sieve](http://docs.debops.org/en/latest/ansible/roles/ansible-dovecot/docs/guides.html#enable-server-side-mail-filtering-with-sieve)
